### PR TITLE
Added NULL pointer check on MultiRecord_Area

### LINKED ISSUE #15: Crashes when called with -b
Hi,

fru-dump crashes when called with -b:
root:~# ./fru-dump -v -b -i /sys/bus/i2c/devices/0-0050/eeprom
read 256 bytes from /sys/bus/i2c/devices/0-0050/eeprom
Date of Man     : Mon Jan  1 00:00:00 1996
Manufacturer    : XXXXXXX
Product Name    : XXXXXXX
Serial Number   :  
Part Number     :  
FRU File ID     :  
Custom Fields:
  Field 0 (len=2): 61 00  |a.|
Segmentation fault

The simple reason is that a NULL-pointer check in free_FRU is missing. I can provide a patch if that's of interest,
CU,
Uli

### PR DESCRIPTION
**Pull request by ulrich-teichert-kk**
Added NULL pointer check on MultiRecord_Area before freeing sub records. Fixes #15

### CODE REVIEW

**Review by nunojsa — APPROVED** [review]
Thanks for the patch!

Could you just refine a bit the commit message? I mean, give it a proper title like "fru: fix NULL ptr dereference". And then in the commit message explain that an additional check is needed and then yes, referencing the link to the issue.

**Comment by ulrich-teichert-kk** [comment]
Sure, will elaborate

**Comment by ulrich-teichert-kk** [comment]
The commit message should be OK now, anything else I can do?

**Review by nunojsa — APPROVED** [review]

**Comment by nunojsa** [comment]
> The commit message should be OK now, anything else I can do?

Yes, it's good! Thx for the patch

**Pull request merged**
