### PR TITLE
do not artificially limit read_file() to 1024

### PR DESCRIPTION
**Pull request by FedericoVaga**
The FRU can be placed on EEPROMs of different sizes, just read the entire file.

Signed-off-by: Federico Vaga <federico.vaga@cern.ch>

### CODE REVIEW

**Comment by dNechita** [comment]
Looks good to me.
Will merge this tomorrow in nobody has any objections.

**Comment by rgetz** [comment]
According to the FCM spec - no they can not.

ANSI/VITA 57.1
FPGA Mezzanine Card (FMC)
Standard

image

The only want to map to that I2C address is to use 256 byte EEPROMs.

I'm not sure I would accept this, unless I understand the use case better.

-Robin

**Comment by FedericoVaga** [comment]
Sorry for the very late answer, I never received the notification.

> The only want to map to that I2C address is to use 256 byte EEPROMs.
> 
> I'm not sure I would accept this, unless I understand the use case better.

The VITA 57.1 is cryptic about the EEPROM size, but through the FRU specification it was implying that the EEPROM must be 256Bytes. Because of this lack of clarity it is not rare to find a bigger EEPROM on FMC modules. With the latest revision (ANSI/VITA 57.1-2019) the valid EEPROMs are 2K or 32K.

image

**Comment by rgetz** [comment]
yes - I was looking at the older spec - this looks fine to me...

**Pull request merged**
